inspector:
    ingestion_key: '%env(INSPECTOR_INGESTION_KEY)%'
    enabled: false
    transport: async
    ignore_routes:
        - '/_wdt*'
        - '/_profiler*'
    ignore_commands:
        - '*'
