services:
    packagist.psr18_client:
        class: Symfony\Component\HttpClient\Psr18Client
        arguments: ['@packagist.client']

    Packagist\Api\Client:
        arguments:
            $httpClient: '@packagist.psr18_client'
