# .symfony.local.yaml
workers:

  # built-in command that starts messenger consumer
   messenger_consume_async:
       cmd: ['symfony', 'console', 'messenger:consume', 'meili', 'async']
       watch: ['config', 'src', 'templates', 'vendor']
   messenger_consume_load_composer:
       cmd: ['symfony', 'console', 'messenger:consume', 'load_composer']
       watch: ['config', 'src', 'templates', 'vendor']



#  messenger_consume_async: ~

#  # you can also add your own custom commands
#  build_spa:
#    cmd: ['npm', '--cwd', './spa/', 'dev']

