survos_commands: {path: /commands, controller: 'Survos\CommandBundle\Controller\CommandController::commands'}
survos_command: {path: "/command/{commandName}", controller: 'Survos\CommandBundle\Controller\CommandController::runCommand'}
