<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250803120402 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE book (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) DEFAULT NULL, isbn VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE endpoint (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, label VARCHAR(255) NOT NULL, columns INT NOT NULL, settings JSONB NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE package (id VARCHAR(255) NOT NULL, data JSON DEFAULT NULL, vendor VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, version VARCHAR(255) DEFAULT NULL, last_updated_on_packagist TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, short_name VARCHAR(255) NOT NULL, symfony_versions JSON DEFAULT NULL, stars INT DEFAULT NULL, php_versions JSON DEFAULT NULL, last_modified_time TIME(0) WITHOUT TIME ZONE DEFAULT NULL, php_version_string VARCHAR(255) DEFAULT NULL, repo VARCHAR(255) DEFAULT NULL, replacement VARCHAR(255) DEFAULT NULL, php_unit_version_string VARCHAR(255) DEFAULT NULL, php_unit_versions JSON DEFAULT NULL, symfony_version_string VARCHAR(255) DEFAULT NULL, packagist_data JSON DEFAULT NULL, source_type VARCHAR(8) DEFAULT NULL, source_url VARCHAR(255) DEFAULT NULL, downloads INT DEFAULT NULL, name VARCHAR(255) NOT NULL, marking VARCHAR(32) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE book');
        $this->addSql('DROP TABLE endpoint');
        $this->addSql('DROP TABLE package');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
